// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20241031104508_up = [
  InsertTable('StoreModel'),
  InsertTable('ExpensesModel'),
  InsertTable('RentModel'),
  InsertTable('ItemModel'),
  InsertTable('_brick_SalaryModel_items'),
  InsertTable('_brick_SalaryModel_deductions'),
  InsertTable('SalaryModel'),
  InsertTable('RentItemModel'),
  InsertTable('PresenceModel'),
  InsertTable('DuePaymentModel'),
  InsertTable('CustomerModel'),
  InsertTable('UserModel'),
  InsertTable('RequestModel'),
  InsertTable('_brick_PenjualanModel_items'),
  InsertTable('PenjualanModel'),
  InsertTable('ProductItemModel'),
  InsertTable('ItemSalary'),
  InsertColumn('title', Column.varchar, onTable: 'StoreModel'),
  InsertColumn('description', Column.varchar, onTable: 'StoreModel'),
  InsertColumn('phone', Column.varchar, onTable: 'StoreModel'),
  InsertColumn('footer', Column.varchar, onTable: 'StoreModel'),
  InsertColumn('sub_footer', Column.varchar, onTable: 'StoreModel'),
  InsertColumn('id', Column.integer, onTable: 'StoreModel', unique: true),
  InsertColumn('title', Column.varchar, onTable: 'ExpensesModel'),
  InsertColumn('note', Column.varchar, onTable: 'ExpensesModel'),
  InsertColumn('amount', Column.integer, onTable: 'ExpensesModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'ExpensesModel'),
  InsertColumn('id', Column.integer, onTable: 'ExpensesModel', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'RentModel'),
  InsertColumn('item', Column.integer, onTable: 'RentModel'),
  InsertColumn('note', Column.varchar, onTable: 'RentModel'),
  InsertColumn('amount', Column.integer, onTable: 'RentModel'),
  InsertColumn('pinalty', Column.integer, onTable: 'RentModel'),
  InsertColumn('identity', Column.boolean, onTable: 'RentModel'),
  InsertColumn('picture', Column.boolean, onTable: 'RentModel'),
  InsertColumn('paid', Column.boolean, onTable: 'RentModel'),
  InsertColumn('how_many_day', Column.integer, onTable: 'RentModel'),
  InsertColumn('rent_date', Column.datetime, onTable: 'RentModel'),
  InsertColumn('updated_at', Column.datetime, onTable: 'RentModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'RentModel'),
  InsertColumn('id', Column.integer, onTable: 'RentModel', unique: true),
  InsertColumn('nama', Column.varchar, onTable: 'ItemModel'),
  InsertColumn('code', Column.varchar, onTable: 'ItemModel'),
  InsertColumn('deskripsi', Column.varchar, onTable: 'ItemModel'),
  InsertColumn('jumlah_barang', Column.integer, onTable: 'ItemModel'),
  InsertColumn('quantity', Column.integer, onTable: 'ItemModel'),
  InsertColumn('ukuran', Column.varchar, onTable: 'ItemModel'),
  InsertColumn('harga_dasar', Column.integer, onTable: 'ItemModel'),
  InsertColumn('harga_jual', Column.integer, onTable: 'ItemModel'),
  InsertColumn('harga_jual_persen', Column.Double, onTable: 'ItemModel'),
  InsertColumn('diskon_persen', Column.Double, onTable: 'ItemModel'),
  InsertColumn('is_harga_jual_persen', Column.boolean, onTable: 'ItemModel'),
  InsertColumn('barang_masuk', Column.datetime, onTable: 'ItemModel'),
  InsertColumn('barang_keluar', Column.datetime, onTable: 'ItemModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'ItemModel'),
  InsertColumn('id', Column.integer, onTable: 'ItemModel', unique: true),
  InsertForeignKey('_brick_SalaryModel_items', 'SalaryModel', foreignKeyColumn: 'l_SalaryModel_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_SalaryModel_items', 'ItemSalary', foreignKeyColumn: 'f_ItemSalary_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_SalaryModel_deductions', 'SalaryModel', foreignKeyColumn: 'l_SalaryModel_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_SalaryModel_deductions', 'ItemSalary', foreignKeyColumn: 'f_ItemSalary_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('user_id', Column.integer, onTable: 'SalaryModel'),
  InsertColumn('status', Column.varchar, onTable: 'SalaryModel'),
  InsertColumn('periode', Column.varchar, onTable: 'SalaryModel'),
  InsertColumn('total', Column.integer, onTable: 'SalaryModel'),
  InsertColumn('note', Column.varchar, onTable: 'SalaryModel'),
  InsertColumn('management', Column.varchar, onTable: 'SalaryModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'SalaryModel'),
  InsertColumn('id', Column.integer, onTable: 'SalaryModel', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'RentItemModel'),
  InsertColumn('code', Column.varchar, onTable: 'RentItemModel'),
  InsertColumn('note', Column.varchar, onTable: 'RentItemModel'),
  InsertColumn('jumlah_barang', Column.integer, onTable: 'RentItemModel'),
  InsertColumn('rent_three_day', Column.integer, onTable: 'RentItemModel'),
  InsertColumn('rent_one_week', Column.integer, onTable: 'RentItemModel'),
  InsertColumn('rent_one_month', Column.integer, onTable: 'RentItemModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'RentItemModel'),
  InsertColumn('id', Column.integer, onTable: 'RentItemModel', unique: true),
  InsertColumn('user', Column.integer, onTable: 'PresenceModel'),
  InsertColumn('status', Column.varchar, onTable: 'PresenceModel'),
  InsertColumn('note', Column.varchar, onTable: 'PresenceModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'PresenceModel'),
  InsertColumn('path', Column.varchar, onTable: 'PresenceModel'),
  InsertColumn('long', Column.Double, onTable: 'PresenceModel'),
  InsertColumn('lat', Column.Double, onTable: 'PresenceModel'),
  InsertColumn('id', Column.integer, onTable: 'PresenceModel', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'DuePaymentModel'),
  InsertColumn('invoice', Column.varchar, onTable: 'DuePaymentModel'),
  InsertColumn('item_name', Column.varchar, onTable: 'DuePaymentModel'),
  InsertColumn('item_amount', Column.integer, onTable: 'DuePaymentModel'),
  InsertColumn('amount', Column.integer, onTable: 'DuePaymentModel'),
  InsertColumn('status', Column.varchar, onTable: 'DuePaymentModel'),
  InsertColumn('note', Column.varchar, onTable: 'DuePaymentModel'),
  InsertColumn('date_in', Column.datetime, onTable: 'DuePaymentModel'),
  InsertColumn('due_date', Column.datetime, onTable: 'DuePaymentModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'DuePaymentModel'),
  InsertColumn('id', Column.integer, onTable: 'DuePaymentModel', unique: true),
  InsertColumn('nama', Column.varchar, onTable: 'CustomerModel'),
  InsertColumn('phone', Column.varchar, onTable: 'CustomerModel'),
  InsertColumn('ktp', Column.varchar, onTable: 'CustomerModel'),
  InsertColumn('dob', Column.datetime, onTable: 'CustomerModel'),
  InsertColumn('keterangan', Column.varchar, onTable: 'CustomerModel'),
  InsertColumn('status', Column.boolean, onTable: 'CustomerModel'),
  InsertColumn('masuk', Column.datetime, onTable: 'CustomerModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'CustomerModel'),
  InsertColumn('id', Column.integer, onTable: 'CustomerModel', unique: true),
  InsertColumn('nama', Column.varchar, onTable: 'UserModel'),
  InsertColumn('dob', Column.datetime, onTable: 'UserModel'),
  InsertColumn('keterangan', Column.varchar, onTable: 'UserModel'),
  InsertColumn('status', Column.boolean, onTable: 'UserModel'),
  InsertColumn('masuk', Column.datetime, onTable: 'UserModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'UserModel'),
  InsertColumn('id', Column.integer, onTable: 'UserModel', unique: true),
  InsertColumn('title', Column.varchar, onTable: 'RequestModel'),
  InsertColumn('note', Column.varchar, onTable: 'RequestModel'),
  InsertColumn('status', Column.varchar, onTable: 'RequestModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'RequestModel'),
  InsertColumn('id', Column.integer, onTable: 'RequestModel', unique: true),
  InsertForeignKey('_brick_PenjualanModel_items', 'PenjualanModel', foreignKeyColumn: 'l_PenjualanModel_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_PenjualanModel_items', 'ProductItemModel', foreignKeyColumn: 'f_ProductItemModel_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('total_item', Column.integer, onTable: 'PenjualanModel'),
  InsertColumn('total_harga', Column.Double, onTable: 'PenjualanModel'),
  InsertColumn('diskon', Column.Double, onTable: 'PenjualanModel'),
  InsertColumn('kasir', Column.integer, onTable: 'PenjualanModel'),
  InsertColumn('pembeli', Column.integer, onTable: 'PenjualanModel'),
  InsertColumn('keterangan', Column.varchar, onTable: 'PenjualanModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'PenjualanModel'),
  InsertColumn('id', Column.integer, onTable: 'PenjualanModel', unique: true),
  InsertColumn('id', Column.integer, onTable: 'ProductItemModel', unique: true),
  InsertColumn('nama', Column.varchar, onTable: 'ProductItemModel'),
  InsertColumn('code', Column.varchar, onTable: 'ProductItemModel'),
  InsertColumn('deskripsi', Column.varchar, onTable: 'ProductItemModel'),
  InsertColumn('jumlah_barang', Column.integer, onTable: 'ProductItemModel'),
  InsertColumn('quantity', Column.integer, onTable: 'ProductItemModel'),
  InsertColumn('ukuran', Column.varchar, onTable: 'ProductItemModel'),
  InsertColumn('harga_dasar', Column.integer, onTable: 'ProductItemModel'),
  InsertColumn('harga_jual', Column.integer, onTable: 'ProductItemModel'),
  InsertColumn('harga_jual_persen', Column.Double, onTable: 'ProductItemModel'),
  InsertColumn('diskon_persen', Column.Double, onTable: 'ProductItemModel'),
  InsertColumn('is_harga_jual_persen', Column.boolean, onTable: 'ProductItemModel'),
  InsertColumn('barang_masuk', Column.datetime, onTable: 'ProductItemModel'),
  InsertColumn('barang_keluar', Column.datetime, onTable: 'ProductItemModel'),
  InsertColumn('created_at', Column.datetime, onTable: 'ProductItemModel'),
  InsertColumn('id', Column.integer, onTable: 'ItemSalary', unique: true),
  InsertColumn('description', Column.varchar, onTable: 'ItemSalary'),
  InsertColumn('amount', Column.varchar, onTable: 'ItemSalary'),
  CreateIndex(columns: ['id'], onTable: 'StoreModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'ExpensesModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RentModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'ItemModel', unique: true),
  CreateIndex(columns: ['l_SalaryModel_brick_id', 'f_ItemSalary_brick_id'], onTable: '_brick_SalaryModel_items', unique: true),
  CreateIndex(columns: ['l_SalaryModel_brick_id', 'f_ItemSalary_brick_id'], onTable: '_brick_SalaryModel_deductions', unique: true),
  CreateIndex(columns: ['id'], onTable: 'SalaryModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RentItemModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'PresenceModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'DuePaymentModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'CustomerModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UserModel', unique: true),
  CreateIndex(columns: ['id'], onTable: 'RequestModel', unique: true),
  CreateIndex(columns: ['l_PenjualanModel_brick_id', 'f_ProductItemModel_brick_id'], onTable: '_brick_PenjualanModel_items', unique: true),
  CreateIndex(columns: ['id'], onTable: 'PenjualanModel', unique: true)
];

const List<MigrationCommand> _migration_20241031104508_down = [
  DropTable('StoreModel'),
  DropTable('ExpensesModel'),
  DropTable('RentModel'),
  DropTable('ItemModel'),
  DropTable('_brick_SalaryModel_items'),
  DropTable('_brick_SalaryModel_deductions'),
  DropTable('SalaryModel'),
  DropTable('RentItemModel'),
  DropTable('PresenceModel'),
  DropTable('DuePaymentModel'),
  DropTable('CustomerModel'),
  DropTable('UserModel'),
  DropTable('RequestModel'),
  DropTable('_brick_PenjualanModel_items'),
  DropTable('PenjualanModel'),
  DropTable('ProductItemModel'),
  DropTable('ItemSalary'),
  DropColumn('title', onTable: 'StoreModel'),
  DropColumn('description', onTable: 'StoreModel'),
  DropColumn('phone', onTable: 'StoreModel'),
  DropColumn('footer', onTable: 'StoreModel'),
  DropColumn('sub_footer', onTable: 'StoreModel'),
  DropColumn('id', onTable: 'StoreModel'),
  DropColumn('title', onTable: 'ExpensesModel'),
  DropColumn('note', onTable: 'ExpensesModel'),
  DropColumn('amount', onTable: 'ExpensesModel'),
  DropColumn('created_at', onTable: 'ExpensesModel'),
  DropColumn('id', onTable: 'ExpensesModel'),
  DropColumn('name', onTable: 'RentModel'),
  DropColumn('item', onTable: 'RentModel'),
  DropColumn('note', onTable: 'RentModel'),
  DropColumn('amount', onTable: 'RentModel'),
  DropColumn('pinalty', onTable: 'RentModel'),
  DropColumn('identity', onTable: 'RentModel'),
  DropColumn('picture', onTable: 'RentModel'),
  DropColumn('paid', onTable: 'RentModel'),
  DropColumn('how_many_day', onTable: 'RentModel'),
  DropColumn('rent_date', onTable: 'RentModel'),
  DropColumn('updated_at', onTable: 'RentModel'),
  DropColumn('created_at', onTable: 'RentModel'),
  DropColumn('id', onTable: 'RentModel'),
  DropColumn('nama', onTable: 'ItemModel'),
  DropColumn('code', onTable: 'ItemModel'),
  DropColumn('deskripsi', onTable: 'ItemModel'),
  DropColumn('jumlah_barang', onTable: 'ItemModel'),
  DropColumn('quantity', onTable: 'ItemModel'),
  DropColumn('ukuran', onTable: 'ItemModel'),
  DropColumn('harga_dasar', onTable: 'ItemModel'),
  DropColumn('harga_jual', onTable: 'ItemModel'),
  DropColumn('harga_jual_persen', onTable: 'ItemModel'),
  DropColumn('diskon_persen', onTable: 'ItemModel'),
  DropColumn('is_harga_jual_persen', onTable: 'ItemModel'),
  DropColumn('barang_masuk', onTable: 'ItemModel'),
  DropColumn('barang_keluar', onTable: 'ItemModel'),
  DropColumn('created_at', onTable: 'ItemModel'),
  DropColumn('id', onTable: 'ItemModel'),
  DropColumn('l_SalaryModel_brick_id', onTable: '_brick_SalaryModel_items'),
  DropColumn('f_ItemSalary_brick_id', onTable: '_brick_SalaryModel_items'),
  DropColumn('l_SalaryModel_brick_id', onTable: '_brick_SalaryModel_deductions'),
  DropColumn('f_ItemSalary_brick_id', onTable: '_brick_SalaryModel_deductions'),
  DropColumn('user_id', onTable: 'SalaryModel'),
  DropColumn('status', onTable: 'SalaryModel'),
  DropColumn('periode', onTable: 'SalaryModel'),
  DropColumn('total', onTable: 'SalaryModel'),
  DropColumn('note', onTable: 'SalaryModel'),
  DropColumn('management', onTable: 'SalaryModel'),
  DropColumn('created_at', onTable: 'SalaryModel'),
  DropColumn('id', onTable: 'SalaryModel'),
  DropColumn('name', onTable: 'RentItemModel'),
  DropColumn('code', onTable: 'RentItemModel'),
  DropColumn('note', onTable: 'RentItemModel'),
  DropColumn('jumlah_barang', onTable: 'RentItemModel'),
  DropColumn('rent_three_day', onTable: 'RentItemModel'),
  DropColumn('rent_one_week', onTable: 'RentItemModel'),
  DropColumn('rent_one_month', onTable: 'RentItemModel'),
  DropColumn('created_at', onTable: 'RentItemModel'),
  DropColumn('id', onTable: 'RentItemModel'),
  DropColumn('user', onTable: 'PresenceModel'),
  DropColumn('status', onTable: 'PresenceModel'),
  DropColumn('note', onTable: 'PresenceModel'),
  DropColumn('created_at', onTable: 'PresenceModel'),
  DropColumn('path', onTable: 'PresenceModel'),
  DropColumn('long', onTable: 'PresenceModel'),
  DropColumn('lat', onTable: 'PresenceModel'),
  DropColumn('id', onTable: 'PresenceModel'),
  DropColumn('name', onTable: 'DuePaymentModel'),
  DropColumn('invoice', onTable: 'DuePaymentModel'),
  DropColumn('item_name', onTable: 'DuePaymentModel'),
  DropColumn('item_amount', onTable: 'DuePaymentModel'),
  DropColumn('amount', onTable: 'DuePaymentModel'),
  DropColumn('status', onTable: 'DuePaymentModel'),
  DropColumn('note', onTable: 'DuePaymentModel'),
  DropColumn('date_in', onTable: 'DuePaymentModel'),
  DropColumn('due_date', onTable: 'DuePaymentModel'),
  DropColumn('created_at', onTable: 'DuePaymentModel'),
  DropColumn('id', onTable: 'DuePaymentModel'),
  DropColumn('nama', onTable: 'CustomerModel'),
  DropColumn('phone', onTable: 'CustomerModel'),
  DropColumn('ktp', onTable: 'CustomerModel'),
  DropColumn('dob', onTable: 'CustomerModel'),
  DropColumn('keterangan', onTable: 'CustomerModel'),
  DropColumn('status', onTable: 'CustomerModel'),
  DropColumn('masuk', onTable: 'CustomerModel'),
  DropColumn('created_at', onTable: 'CustomerModel'),
  DropColumn('id', onTable: 'CustomerModel'),
  DropColumn('nama', onTable: 'UserModel'),
  DropColumn('dob', onTable: 'UserModel'),
  DropColumn('keterangan', onTable: 'UserModel'),
  DropColumn('status', onTable: 'UserModel'),
  DropColumn('masuk', onTable: 'UserModel'),
  DropColumn('created_at', onTable: 'UserModel'),
  DropColumn('id', onTable: 'UserModel'),
  DropColumn('title', onTable: 'RequestModel'),
  DropColumn('note', onTable: 'RequestModel'),
  DropColumn('status', onTable: 'RequestModel'),
  DropColumn('created_at', onTable: 'RequestModel'),
  DropColumn('id', onTable: 'RequestModel'),
  DropColumn('l_PenjualanModel_brick_id', onTable: '_brick_PenjualanModel_items'),
  DropColumn('f_ProductItemModel_brick_id', onTable: '_brick_PenjualanModel_items'),
  DropColumn('total_item', onTable: 'PenjualanModel'),
  DropColumn('total_harga', onTable: 'PenjualanModel'),
  DropColumn('diskon', onTable: 'PenjualanModel'),
  DropColumn('kasir', onTable: 'PenjualanModel'),
  DropColumn('pembeli', onTable: 'PenjualanModel'),
  DropColumn('keterangan', onTable: 'PenjualanModel'),
  DropColumn('created_at', onTable: 'PenjualanModel'),
  DropColumn('id', onTable: 'PenjualanModel'),
  DropColumn('id', onTable: 'ProductItemModel'),
  DropColumn('nama', onTable: 'ProductItemModel'),
  DropColumn('code', onTable: 'ProductItemModel'),
  DropColumn('deskripsi', onTable: 'ProductItemModel'),
  DropColumn('jumlah_barang', onTable: 'ProductItemModel'),
  DropColumn('quantity', onTable: 'ProductItemModel'),
  DropColumn('ukuran', onTable: 'ProductItemModel'),
  DropColumn('harga_dasar', onTable: 'ProductItemModel'),
  DropColumn('harga_jual', onTable: 'ProductItemModel'),
  DropColumn('harga_jual_persen', onTable: 'ProductItemModel'),
  DropColumn('diskon_persen', onTable: 'ProductItemModel'),
  DropColumn('is_harga_jual_persen', onTable: 'ProductItemModel'),
  DropColumn('barang_masuk', onTable: 'ProductItemModel'),
  DropColumn('barang_keluar', onTable: 'ProductItemModel'),
  DropColumn('created_at', onTable: 'ProductItemModel'),
  DropColumn('id', onTable: 'ItemSalary'),
  DropColumn('description', onTable: 'ItemSalary'),
  DropColumn('amount', onTable: 'ItemSalary'),
  DropIndex('index_StoreModel_on_id'),
  DropIndex('index_ExpensesModel_on_id'),
  DropIndex('index_RentModel_on_id'),
  DropIndex('index_ItemModel_on_id'),
  DropIndex('index__brick_SalaryModel_items_on_l_SalaryModel_brick_id_f_ItemSalary_brick_id'),
  DropIndex('index__brick_SalaryModel_deductions_on_l_SalaryModel_brick_id_f_ItemSalary_brick_id'),
  DropIndex('index_SalaryModel_on_id'),
  DropIndex('index_RentItemModel_on_id'),
  DropIndex('index_PresenceModel_on_id'),
  DropIndex('index_DuePaymentModel_on_id'),
  DropIndex('index_CustomerModel_on_id'),
  DropIndex('index_UserModel_on_id'),
  DropIndex('index_RequestModel_on_id'),
  DropIndex('index__brick_PenjualanModel_items_on_l_PenjualanModel_brick_id_f_ProductItemModel_brick_id'),
  DropIndex('index_PenjualanModel_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20241031104508',
  up: _migration_20241031104508_up,
  down: _migration_20241031104508_down,
)
class Migration20241031104508 extends Migration {
  const Migration20241031104508()
    : super(
        version: 20241031104508,
        up: _migration_20241031104508_up,
        down: _migration_20241031104508_down,
      );
}
